version: "3.7"
services:
  mysql-service:
    image: mysql:8.0.33
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=azship
  web-service:
    build: .
    ports:
      - 8080:8080
    networks:
      - spring-boot-mysql-network   
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge