services:
  web-service:
    build: azship
    context: azship
      target: dev-envs
    ports:
      - 8080:8080
    environment:
      - 'MYSQL_DATABASE=azship'
    networks:
      - spring-boot-mysql-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql-service:
    image: mysql:latest
    restart: always
    networks:
      - spring-boot-mysql-network
    environment:
      - 'MYSQL_DATABASE=azship'
      - 'MYSQL_ROOT_PASSWORD=root'
    expose:
      - 3306
networks:
  spring-boot-mysql-network: